/**
 * Email Integration
 * ==================
 * Sends report notification emails via SMTP (works with Gmail App Passwords,
 * SendGrid, Mailgun, or any SMTP provider).
 *
 * Requires in .env:
 *   SMTP_HOST=smtp.gmail.com
 *   SMTP_PORT=465
 *   SMTP_USER=you@gmail.com
 *   SMTP_PASS=your-app-password
 *   EMAIL_TO=you@gmail.com
 */

import nodemailer from "nodemailer";

const SMTP_HOST = process.env.SMTP_HOST ?? "";
const SMTP_PORT = Number(process.env.SMTP_PORT || 465);
const SMTP_USER = process.env.SMTP_USER ?? "";
const SMTP_PASS = process.env.SMTP_PASS ?? "";
const EMAIL_TO = process.env.EMAIL_TO ?? "";

export function isEmailConfigured(): boolean {
  return !!(SMTP_HOST && SMTP_USER && SMTP_PASS && EMAIL_TO);
}

function createTransport() {
  return nodemailer.createTransport({
    host: SMTP_HOST,
    port: SMTP_PORT,
    secure: SMTP_PORT === 465,
    auth: { user: SMTP_USER, pass: SMTP_PASS },
  });
}

/**
 * Send a report notification email.
 * Includes an executive summary in the email body
 * and the full report as an inline markdown attachment.
 */
export async function sendReportEmail(params: {
  company: string;
  report: string;
  riskScore?: number;
  notionUrl?: string;
}): Promise<{ messageId: string }> {
  const transport = createTransport();
  const today = new Date().toISOString().split("T")[0];

  // Extract executive summary (first ~500 chars after first heading)
  const execMatch = params.report.match(/Executive Summary[\s\S]*?\n\n([\s\S]{0,600})/i);
  const excerpt = execMatch?.[1]?.trim() ?? params.report.slice(0, 500);

  const notionLink = params.notionUrl
    ? `<p><a href="${params.notionUrl}">View full report in Notion</a></p>`
    : "";

  const html = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 640px;">
      <h2 style="color: #1a1a1a;">${params.company} — Investment Analysis Ready</h2>
      <p style="color: #666; font-size: 14px;">${today} | Risk Score: ${params.riskScore ?? "N/A"}/10</p>
      <hr style="border: none; border-top: 1px solid #e0e0e0;" />
      <h3 style="color: #333;">Executive Summary</h3>
      <p style="color: #444; line-height: 1.6;">${excerpt.replace(/\n/g, "<br>")}</p>
      ${notionLink}
      <hr style="border: none; border-top: 1px solid #e0e0e0;" />
      <p style="color: #999; font-size: 12px;">
        Full report attached as Markdown. Generated by Multi-Agent Research System.
      </p>
    </div>
  `;

  const slug = params.company.toLowerCase().replace(/\s+/g, "_");
  const result = await transport.sendMail({
    from: `"AI Investment Analyst" <${SMTP_USER}>`,
    to: EMAIL_TO,
    subject: `[Report] ${params.company} Investment Analysis — ${today}`,
    html,
    attachments: [
      {
        filename: `${slug}_report_${today}.md`,
        content: params.report,
        contentType: "text/markdown",
      },
    ],
  });

  return { messageId: result.messageId };
}
